

DELETE http://localhost:3003/api/blogs/66995b0794716b975fdd21be
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2OGVmYzNkYzBiN2NhMDVjODY5NWViOCIsImlhdCI6MTcyMTMzMDkzMSwiZXhwIjoxNzIxMzM0NTMxfQ.zDmdg-j5ZS8Y64yWGWIcWe_fwn-c8XQvHYzkV5OFCLY